name: meal_planning_app_getx
description: A Flutter project that helps you manage your meals, recipes, groceries and fridge.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  animate_gradient: ^0.0.2+1
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true